### ISSUE TITLE
暗黑模式动态颜色  设置导航栏颜色存在问题  self.gk_navBackgroundColor = UIColor.dynamicColor_FFFFFF_111111()

### ISSUE THREAD

**Issue by dulifu** [QuintGao/GKNavigationBarSwift#1]

**Comment by QuintGao** [comment]
有什么问题？

**Comment by dulifu** [comment]
切换模式，导航条动态颜色不会变化，我设置动态颜色的


//MARK: -白色导航条背景色

&nbsp; &nbsp; static func dynamicColor_FFFFFF_111111() -&gt; UIColor {

&nbsp; &nbsp; &nbsp; &nbsp; return UIColor.generateDynamicColor(colorWithHexString("#FFFFFF"), colorWithHexString("#111111"))

&nbsp; &nbsp; }



调用

self.gk_navBackgroundColor = UIColor.dynamicColor_FFFFFF_111111()





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "QuintGao"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 中午11:09
收件人: "QuintGao/GKNavigationBarSwift"<GKNavigationBarSwift@noreply.github.com&gt;; 
抄送: "下线的时候"<1070192262@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [QuintGao/GKNavigationBarSwift] 暗黑模式动态颜色  设置导航栏颜色存在问题  self.gk_navBackgroundColor = UIColor.dynamicColor_FFFFFF_111111() (#1)





 
有什么问题？

**Comment by dulifu** [comment]
会不会是内部用的CGColor，暗黑模式CGColor是单一颜色，swift才初学，不太懂

**Comment by QuintGao** [comment]
gk_navBackgroundColor、gk_navShadowColor、gk_navTitleColor 这三个属性不支持动态颜色，你可以在viewController的traitCollectionDidChange方法中重新赋值

**Comment by dulifu** [comment]
好的  @QuintGao
