### ISSUE TITLE
 xcode 运行不起来

### ISSUE THREAD

**Issue by jaylanlu** [QuintGao/GKNavigationBarSwift#11]
error opening input file '/Users/gaokun/mine/GKNavigationBarSwift/Example/Example/Example-Bridging-Header.h' (No such file or directory)
<unknown>:0: error: cannot open file '/Users/didi/Library/Developer/Xcode/DerivedData/GKNavigationBarSwift-fakrnjgeyfspgmdvquqnytjklrml/Build/Intermediates.noindex/PrecompiledHeaders/Example-Bridging-Header-1RRN7IVVY697J.dia' for diagnostics emission (No such file or directory)

**Comment by QuintGao** [comment]
已修复
