### ISSUE TITLE
返回手势设置无效

### ISSUE THREAD

**Issue by tyshui** [QuintGao/GKNavigationBarSwift#12]
gk_interactivePopDisabled = false // 禁止滑动(true - 禁止)
     gk_fullScreenPopDisabled = false  // 禁止全屏滑动，支持边缘滑动 (true - 禁止)
     
     
     在ViewController设置，没有手势返回

**Comment by QuintGao** [comment]
请确认是否通过public convenience init(rootVC: UIViewController)方法初始化导航栏

**Comment by tyshui** [comment]
通过 BaseNavigationController: UINavigationController ，使用public convenience init(rootVC: UIViewController)初始化，不能使用BaseNavigationController创建初始化，这样初始化了，手势将无效

**Comment by QuintGao** [comment]
你怎么初始化的，我这测试没问题

**Comment by RuYiChenIT** [comment]
一会儿 我在测试下，发你，谢谢

**Comment by RuYiChenIT** [comment]
> 你怎么初始化的，我这测试没问题

**Comment by RuYiChenIT** [comment]
我在测试下， 一会儿发你， 稍等， 谢谢🙏

**Comment by tyshui** [comment]
好的，感谢

**Comment by SleepyCatZz** [comment]
> 通过 BaseNavigationController: UINavigationController ，使用public convenience init(rootVC: UIViewController)初始化，不能使用BaseNavigationController创建初始化，这样初始化了，手势将无效
要是使用 BaseNavigationController: UINavigationController 的方法来初始化，那我该怎么改


> 通过 BaseNavigationController: UINavigationController ，使用public convenience init(rootVC: UIViewController)初始化，不能使用BaseNavigationController创建初始化，这样初始化了，手势将无效

找了半天，原来需要使用public convenience init(rootVC: UIViewController)来初始化，之前用的public convenience init(rootViewController: UIViewController)，手势一直无效

**Comment by QuintGao** [comment]
> > 通过 BaseNavigationController: UINavigationController ，使用public convenience init(rootVC: UIViewController)初始化，不能使用BaseNavigationController创建初始化，这样初始化了，手势将无效
> 
> 找了半天，原来需要使用public convenience init(rootVC: UIViewController)来初始化，之前用的public convenience init(rootViewController: UIViewController)，手势一直无效

是的需要使用public convenience init(rootVC: UIViewController)这个方法初始化导航控制器才能开启手势处理

**Comment by limingnie** [comment]
谁能解释一下两者的区别吗。
