### ISSUE TITLE
用xcode 13.3 打包报错

### ISSUE THREAD

**Issue by tangbing** [QuintGao/GKNavigationBarSwift#16]
直接git clone demo，然后用xcode 13.3真机打包，直接报错，
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/11678386/159236857-ff730e19-abb2-4f7c-adfa-84d99d03e75f.png">

**Comment by QuintGao** [comment]
更新一下呢 我这没问题

**Comment by tangbing** [comment]
用旧版本Xcode，就ok了
