### ISSUE TITLE
切换控制器，状态栏白色一闪而过

### ISSUE THREAD

**Issue by tangbing** [QuintGao/GKNavigationBarSwift#17]
https://user-images.githubusercontent.com/11678386/160114356-8b3c629d-0d7c-44ea-81df-3270f47abb02.mp4

奇怪，一样的代码，另外一个界面，都不会

也在基类控制器写了下面代码，还是会出现
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    
    self.gk_statusBarStyle = .lightContent
}

**Comment by QuintGao** [comment]
有demo吗 ，我这里没复现
