### ISSUE TITLE
系统tabbar多个子控制器， 基类设置状态栏lightcontent，发现tabbar首次进入，状态栏总是先黑一会再变白

### ISSUE THREAD

**Issue by dulifu** [QuintGao/GKNavigationBarSwift#2]
<img width="1106" alt="截屏2020-08-06 下午4 36 36" src="https://user-images.githubusercontent.com/17981102/89510487-368e0500-d803-11ea-9e13-4dadf80b4f42.png">

**Comment by QuintGao** [comment]
尽量在初始化控制器的时候就设置gk_statusBarStyle
