### ISSUE TITLE
用了  GKNavigationBar 的页面 setNavigationBarHidden 设置无效了

### ISSUE THREAD

**Issue by syxc** [QuintGao/GKNavigationBarSwift#21]
如题，用了  GKNavigationBar 的页面 setNavigationBarHidden 设置无效

现象：
没有使用 GKNavigationBar 的 UIViewController 中调用 setNavigationBarHidden 正常
使用了 GKNavigationBar 的 UIViewController 中调用 setNavigationBarHidden 无效

Swift: 5.0
iOS: 15
Xcode: 13.4

**Comment by QuintGao** [comment]
这个是自定义的导航栏，想隐藏用self.gk_navigationBar.isHidden = true

**Comment by syxc** [comment]
> 这个是自定义的导航栏，想隐藏用self.gk_navigationBar.isHidden = true

好的，我试下，多谢。
