### ISSUE TITLE
为什么此处不做实现呢？

### ISSUE THREAD

**Issue by ghosthk** [QuintGao/GKNavigationBarSwift#22]
GKNavigationBarSwift.swift 文件
```
    required public init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

**Comment by QuintGao** [comment]
这个方法使用xib创建时才会调用，目前没有用到

**Comment by ghosthk** [comment]
> 这个方法使用xib创建时才会调用，目前没有用到

有没有可能实现下？要么得手动创建，直接在xib上把navigationbar设置为GKNavigationBar，还是方便些。
要么得把库搞成本地库了。

**Comment by QuintGao** [comment]
1、我这个是把系统导航栏隐藏，然后在每个页面添加自定义导航栏，如果用xib的话你每个页面都自己添加吗？
2、内部会自动创建GKNavigationBar，你只需要调用跟导航栏相关的方法即可

**Comment by ghosthk** [comment]
> 1、我这个是把系统导航栏隐藏，然后在每个页面添加自定义导航栏，如果用xib的话你每个页面都自己添加吗？ 2、内部会自动创建GKNavigationBar，你只需要调用跟导航栏相关的方法即可

嗯。跑去看了下源码，的确是你说的这样，会自动创建navigationbar，之前理解错了。
