### ISSUE TITLE
后退按钮图标坐标会跳动

### ISSUE THREAD

**Issue by syxc** [QuintGao/GKNavigationBarSwift#23]
场景：
点击 tableCell 弹出 UIAlertController，在 present 出 UIAlertController 时，gk_navLeftBarButtonItem 对应的 UIBarButtonItem 的图标坐标会往左移动一点距离，这个在之前的版本中没有出现过这个问题（之前用的 1.4.3）

**Comment by syxc** [comment]
![image](https://user-images.githubusercontent.com/315633/182377045-6f48b7cf-f4f2-440d-9565-2fe6e634a0cd.png)

如图，注释这两行以后，就不会出现我描述的那个问题了，仅供参考，望修复。

**Comment by QuintGao** [comment]
刚试了 没发现你说的情况，你那边用的最新版吗，另外看看我demo能否复现

**Comment by syxc** [comment]
> 刚试了 没发现你说的情况，你那边用的最新版吗，另外看看我demo能否复现

目前用的是 1.5.1，在我们的实际项目中，我描述的那个场景及现象存在，但实际项目的 demo 不方便提供，不然我可以给你个 demo 的。
我们的实际项目中，我把我截图中标注出来的两行代码注释后就能正常。

**Comment by syxc** [comment]
> 刚试了 没发现你说的情况，你那边用的最新版吗，另外看看我demo能否复现

你的 demo，我回头抽时间看下能否在上边复现我说的问题。

**Comment by syxc** [comment]
升级到 [1.5.4](https://github.com/QuintGao/GKNavigationBarSwift/releases/tag/1.5.4) 后，这个问题已经不会出现了。
