### ISSUE TITLE
侧滑返回失效

### ISSUE THREAD

**Issue by ryanranya** [QuintGao/GKNavigationBarSwift#25]
侧滑返回失效。我集成了之后使用默认配置GKConfigure.setupDefault()，但是我再页面里面如果使用了self.gk_navigationItem.title = "详情"self.gk_statusBarStyle = .default但是我在这个页面侧滑返回失效，使用系统的可以

**Comment by QuintGao** [comment]
导航控制器怎么创建的？

**Comment by ryanranya** [comment]
![image](https://user-images.githubusercontent.com/26618638/199640855-5d9c6181-1bcb-461d-995e-e4038041b57b.png)
![image](https://user-images.githubusercontent.com/26618638/199640881-9041a4ce-d549-46bb-bff8-715646ed961b.png)

**Comment by ryanranya** [comment]
就按demo里面直接写的这些，我再详情页面设置了标题和修改barStyle

**Comment by QuintGao** [comment]
let nav = UINavigationController(rootVC: GKMainViewController())
导航控制器是这样初始化的吗

**Comment by ryanranya** [comment]
可以了

**Comment by ryanranya** [comment]
导航器初始化一定要用UINavigationController(rootVC:VC）这个，请注意不然侧滑返回无效
