### ISSUE TITLE
遇到一个问题，present一个Nav带rootVC,Nav dismiss 后 Nav释放了  rootVC 不会释放！

### ISSUE THREAD

**Issue by ys-ocean** [QuintGao/GKNavigationBarSwift#26]
编译后调用
GKConfigure.setupCustom { _ in }

然后viewController调用
let vc = UIViewController()
let nav = UINavigationController(rootViewController: vc )
nav.modalPresentationStyle = .fullScreen
self.present(nav, animated: true, completion: nil)

再调用
nav.dismiss(animated: true)  后  nav释放了  vc 不会释放

**Comment by QuintGao** [comment]
最新版已修复
