### ISSUE TITLE
不知道为什么系统的UINavigationbar和GKNavigationBar共存

### ISSUE THREAD

**Issue by huyabin** [QuintGao/GKNavigationBarSwift#31]
![截屏2023-06-25 09 53 38](https://github.com/QuintGao/GKNavigationBarSwift/assets/13210638/9f5403de-bde2-4073-8c86-f9dce2a99d5c)
版本是
GKNavigationBarSwift (1.5.9)

``` swift
    GKConfigure.setupCustom {

            $0.backgroundColor = .white
            
            $0.backImage = UIImage(named: "ic_bk")
            // 导航栏标题颜色
            $0.titleColor = .black
            // 导航栏标题字体
            $0.titleFont = .systemFont(ofSize: 18)
            // 导航栏返回按钮样式
            $0.backStyle = .black
            // 状态栏样式
            $0.statusBarStyle = .`default`
            // 导航栏左右item间距
            $0.gk_navItemLeftSpace = 10
            $0.gk_navItemRightSpace = 10
            // 是否恢复系统导航
            $0.gk_restoreSystemNavBar = false
            $0.gk_hidesBottomBarWhenPushed = true
            // 缩放配置
//            $0.gk_translationX = 15
//            $0.gk_translationY = 20
            $0.gk_scaleX = 0.90
            $0.gk_scaleY = 0.92
            // 开启全局UIScrollView处理
            $0.gk_openScrollViewGestureHandle = true
        }
        
```
添加childController，这个childController也会存在系统的bar
```swift

        childController.tabBarItem.image = normalImage?.withRenderingMode(.alwaysTemplate)
        childController.tabBarItem.selectedImage = selectedImageName?.withRenderingMode(.alwaysTemplate)
        childController.tabBarItem.title = title
        
        let nav = UINavigationController(rootVC: childController)
        nav.gk_openScrollLeftPush = true
        addChild(nav)

```
push到下一个界面
``` swift
        let vc = xxxx()
        vc.hidesBottomBarWhenPushed = true
        self.navigationController?.pushViewController(vc, animated: true)

```
出问题界面设置代码
```swift
        self.gk_navTitle = "个人信息"
        self.gk_navLineHidden = false
        self.gk_navBackgroundColor = UIColor.hexColor(hex: "#F5F7F7")

```

**Comment by huyabin** [comment]
pod 里的第三方
  pod 'SnapKit' #约束
  pod 'MJRefresh' # 刷新
  pod 'SwiftTheme' # 主题
  pod 'SwiftMessages' # 类似推送的消息弹出
  pod "ESTabBarController-swift"

#  pod 'DropDown'
  pod 'Jelly' # 动画
  pod 'EmptyDataSet-Swift' # https://github.com/Xiaoye220/EmptyDataSet-Swift
  pod 'GKNavigationBarSwift'# 导航的
  pod 'Kingfisher'#图片加载
  
  pod 'SVProgressHUD'
  pod 'Toaster' # 这玩意有bug；横屏用不了，竖屏可以
  pod 'Toast-Swift' # https://github.com/scalessec/Toast-Swift
  pod 'NVActivityIndicatorView/Extended'

  pod 'SwiftDate' #

#  #SYSTEM
#
  pod 'DeviceKit'
  pod 'IQKeyboardManagerSwift', '6.5.6'
  pod 'DefaultsKit' # https://github.com/nmdias/DefaultsKit
  
#  pod 'BluetoothKit' # https://github.com/rhummelmose/BluetoothKit
#  pod 'Bluejay'
#  pod 'RxBluetoothKit'

#  #NETWORK
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Starscream', '~> 4.0.0' #webScoket
  pod 'CocoaAsyncSocket', '~> 7.6.3'

#  #DATA
#  pod 'SwifterSwift'
  pod 'CleanJSON'
  pod 'R.swift' # https://github.com/mac-cain13/R.swift

  # RX
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxBlocking'

  pod 'NSObject+Rx' # https://github.com/RxSwiftCommunity/NSObject-Rx
  pod 'RxURLNavigator' # https://github.com/InsectQY/RxURLNavigator
  pod 'RxDataSources' # https://github.com/RxSwiftCommunity/RxDataSources
  pod 'RxActivityIndicator' # https://github.com/InsectQY/RxActivityIndicator
  pod 'RxReachability' # https://github.com/RxSwiftCommunity/RxReachability
  pod 'RxOptional' # https://github.com/RxSwiftCommunity/RxOptional
  
  
  #DATABASE
  pod 'GRDB.swift/SQLCipher'
  pod 'SQLCipher', '~> 4.0'
  # 国际化
  pod 'Localize-Swift' #本地化 # https://github.com/marmelroy/Localize-Swift
  
  # Test
  pod 'LookinServer', :configurations => ['Debug']
  pod 'CocoaDebug', :configurations => ['Debug']
#  pod 'XCGLogger', '~> 7.0.1'
  pod 'SwiftyBeaver'
#  pod 'Pgyer'
#  pod 'PgyUpdate'
  pod 'SwiftLint'

**Comment by QuintGao** [comment]
检查下哪里是不是把系统导航又显示出来了

**Comment by huyabin** [comment]
没有，没有调用显示系统导航的代码。

**Comment by huyabin** [comment]
重装Xcode好了，不知道啥原因
