### ISSUE TITLE
设置gk_statusBarStyle无效

### ISSUE THREAD

**Issue by bilibili11** [QuintGao/GKNavigationBarSwift#35]
if ZZZ_SleepManager.manager.startSleep(){
            let rootVC = ZZZ_SleepContentViewController()
            rootVC.dissMissBlock = {
                ZZZ_SleepMaskAlertView.init(frame: .zero, startT: ZZZ_SleepManager.manager.startTime!, endT:ZZZ_SleepManager.manager.endTime!).zzz_Show()

            }
//            let vc = UINavigationController(rootVC: rootVC)
            rootVC.modalPresentationStyle = .fullScreen
            self.present(rootVC, animated: true)
        }
如果用//            let vc = UINavigationController(rootVC: rootVC) 设置就会失效,但是demo没有这种情况

**Comment by QuintGao** [comment]
试试我demo能不能复现
