### ISSUE TITLE
iOS 12的手机，自定义返回按钮，设置navItemLeftSpace为0 ，显示还是距左边有一定距离

### ISSUE THREAD

**Issue by sdwangxianwen** [QuintGao/GKNavigationBarSwift#4]
iOS13的手机可以正常显示，但是在iOS12的手机上，navItemLeftSpace设置为0，距离屏幕左边也是有个差不多10的距离

**Comment by QuintGao** [comment]
我试了下，模拟器确实有问题，你用真机试过吗？

**Comment by sdwangxianwen** [comment]
我用的真机，一个iOS13，一个iOS12

**Comment by QuintGao** [comment]
不知道为啥，iOS12中交换方法gk_layoutSubviews没有执行，OC版本是好的

**Comment by sdwangxianwen** [comment]
临时找到的解决方案，iOS12下可以使用，也不影响ios13 
gk_navItemLeftSpace = 15
 gk_navLeftBarButtonItem = UIBarButtonItem(image: UIImage(named: "customback")?.withRenderingMode(.alwaysOriginal), style: .plain, target: self, action: #selector(pop))

**Comment by huyabin** [comment]
iOS12 真机返回按钮距离特别大。13系统没问题。不知道什么原因

**Comment by QuintGao** [comment]
1.2.2 已修复该问题
