### ISSUE TITLE
在Storyboard上控件约束Safe Area.top为44，实际效果控件和导航底部有个5pt的间距

### ISSUE THREAD

**Issue by Gaozn** [QuintGao/GKNavigationBarSwift#41]
iPhone15模拟器

我看到_UINavigationBarContentView的frame是<_UINavigationBarContentView: 0x10466e6f0; frame = (0 **54**; 393 44); layer = <CALayer: 0x6000002a0de0>> layout=0x104662020。
而在在Storyboard上控件约束Safe Area.top为0时，控件的y为**59**

系统导航<_UIVisualEffectBackdropView: 0x105919050; frame = (0 0; 393 **103**); 
GKNavigationBarSwift：<GKNavigationBarSwift.GKNavigationBar: 0x10595dfc0; baseClass = UINavigationBar; frame = (0 0; 393 **98**); 

刚想到新机型状态栏和SafeAreaTop高度是不一样的 状态栏是54、SafeAreaTop是59

**Comment by Gaozn** [comment]
UIViewController+GKExtension.swift
790行 // iPhone 14 Pro 状态栏高度与安全区域高度不一致，这里改为使用状态栏高度

我觉得应该按安全距离算，因为系统的导航就是这样做的

**Comment by QuintGao** [comment]
系统导航栏：UINavigationBar: 0x105c0b9d0; frame = (0 53.6667; 430 44);
安全区域：UIEdgeInsets(top: 59.0, left: 0.0, bottom: 34.0, right: 0.0)
状态栏：(0.0, 0.0, 430.0, 54.0)

这样看系统导航栏的y值就是状态栏的高度

**Comment by Gaozn** [comment]
我改了下源码 感觉这样符合我的需求 
navBarH = max(topH, safeAreaInsetTop) + gkNavBarH
