### ISSUE TITLE
使用Xib创建VC，布局的问题

### ISSUE THREAD

**Issue by liuyang2211** [QuintGao/GKNavigationBarSwift#42]
当我使用Xib创建VC，并简单从safaArea开始布局时，集成GKNavigationBar的VC，不能从导航栏下方开始计算尺寸；但是当我不集成GKNavigationBar，就可以从导航栏下方开始计算尺寸，请问这是有意这样设计的吗？
![截屏2024-09-30 17 19 44](https://github.com/user-attachments/assets/9f094914-80fe-4855-85cf-afc0eeb12bc1)
![Uploading 截屏2024-09-30 17.16.24.png…]()

**Comment by QuintGao** [comment]
因为把系统导航栏隐藏了，所以布局的时候要从自定义导航栏开始布局
