### ISSUE TITLE
（内存泄漏）切换根视图后，之前的控制器不会被销毁

### ISSUE THREAD

**Issue by baozoudiudiu** [QuintGao/GKNavigationBarSwift#5]
设置登录页为根视图
```
let rootvc = UINavigationController(rootVC: NATSignInController.init())
rootvc.gk_openScrollLeftPush = true
self.changeRootViewController(rootvc)
```
登录成功后，切换首页为根视图，`NATSignInController`没有调用deinit方法。
如果我把`let rootvc = UINavigationController(rootVC: NATSignInController.init())`换成系统API`let rootvc = UINavigationController.init(rootViewController: NATSignInController.init())`。切换首页为根视图后，登录控制器调用了deinit方法。

**Comment by QuintGao** [comment]
问题已修复
