### ISSUE TITLE
self.navigationController?.navigationBar.isTranslucent = false; 无效

### ISSUE THREAD

**Issue by shunqiziran199202** [QuintGao/GKNavigationBarSwift#7]
但我使用 这个第三方时，导航栏会遮挡view，这时设置 self.navigationController?.navigationBar.isTranslucent = false; 是没有作用。
我查看demo中是设置view的顶部距离视图顶部  导航栏高度+状态栏高度。
有没有办法可以不用设置距离，直接就让 self.navigationController?.navigationBar.isTranslucent = false; 起作用

**Comment by QuintGao** [comment]
你用的系统的导航栏？我这应该不会影响系统导航栏的
