### ISSUE TITLE
继承UITabBarController后，preferredStatusBarStyle方法没触发，碰到这个奇怪的问题。纳闷！

### ISSUE THREAD

**Issue by ETmanwenhan** [QuintGao/GKNavigationBarSwift#8]
继承系统的UITabBarController后，所以页面的preferredStatusBarStyle方法都没触发。有解决方案吗？

**Comment by QuintGao** [comment]
我这试没问题的

**Comment by ETmanwenhan** [comment]
> 我这试没问题的

可以写到demo里吗？谢谢！

**Comment by ETmanwenhan** [comment]
> 我这试没问题的
继承UITabBarController时，需要添加啥额外的适配吗？

需要类似UINavigationController的分类一样添加额外的UITabBarController分类吗？
```swift
extension UINavigationController {
    open override var childForStatusBarHidden: UIViewController? {
        return topViewController
    }
    
    open override var childForStatusBarStyle: UIViewController? {
        return topViewController
    }
}
```

**Comment by ETmanwenhan** [comment]
> 我这试没问题的

我找到问题了：原因是UINavigationController嵌套导致。UINavigationController包含MainTabBarController、然后MainTabBarController每一个自控制器都创建了一个独立的UINavigationController，这种情况，就会导致切换状态栏样式失效！

**Comment by QuintGao** [comment]
我这测试还是没问题啊，你可以看看最新demo的网易新闻push
